### ISSUE TITLE
v3.0 checklist

### ISSUE THREAD

**Issue by moebiusmania** [bitrockteam/bitrock-website#15]
Things to keep in mind for the next **major iteration**:

- [ ] all main issues from v2.x resolved
- [ ] updated UI
  - [ ] cards with only image and title
  - [ ] different masonry layout
  - [ ] based on the Amber Design System
  - [ ] filter & search posts in home page
  - [ ] better preload animation/effect
- [ ] Content
  - [ ] add "cluster" custom taxonomy

some of this stuff may (or may not) be resolved before the `v3.0 milestone`.
